[package]
name = "decompress_cap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cheri-rust = { path = "cheri-rust" }

[build-dependencies]
dunce = "0.1.1"
bindgen = "*"
